# NGINX Yapılandırması - DevOps En İyi Uygulamaları & Güvenlik Odaklı

server {
    listen 80;
    
    # 1. GÜVENLİK (Security Best Practices)
    server_tokens off; # NGINX sürüm bilgisini gizler 
    # HTTP Güvenlik Başlıkları
    add_header X-Frame-Options "SAMEORIGIN" always; # Clickjacking koruması
    add_header X-XSS-Protection "1; mode=block" always; # Cross-Site Scripting (XSS) koruması
    add_header X-Content-Type-Options "nosniff" always; # MIME-type sniffing koruması
    add_header Referrer-Policy "no-referrer-when-downgrade" always;


    root /usr/share/nginx/html;
    index index.html index.htm;

   
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    location / {
        try_files $uri $uri/ /index.html;
    }


    location /health {
        access_log off; 
        add_header 'Content-Type' 'application/json';
        return 200 '{"status":"UP", "service":"frontend"}';
    }

  
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }


    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}