server {
    listen 80;
    
    # NGINX'in dosyaları sunacağı kök dizin
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # React Router (SPA) için hayati ayar: 
        # Bulamadığın her URL'i index.html'e yönlendir ki React halletsin
        try_files $uri $uri/ /index.html;
    }

    # Hata sayfaları için temel yapılandırma
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}